data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Centrifuge"
public_key = "f60bf544f6fc9cc4e30bacbabb52bbc523d1ad77addf8303b724ad59717d766f"

[[chains]]
name = "centrifuge"
rpc_endpoint = "wss://fullnode.parachain.centrifuge.io"
color = "#fcc367"

[[chains]]
name = "altair"
rpc_endpoint = "wss://fullnode.altair.centrifuge.io"
color = "#ffb700"
